"""Add role_id to column_headers

Revision ID: db4505c5b400
Revises: 
Create Date: 2025-11-08 17:49:42.992601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db4505c5b400'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('column_headers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_column_headers_role_id'), ['role_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('column_headers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_column_headers_role_id'))
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###
